# 出力関数の設計

In [1]:
import numpy as np

In [2]:
# 恒等関数
a = np.array([1, 2, 4, 5])

def identity(a):
    return a

identity(a)

array([1, 2, 4, 5])

In [3]:
# 入力
a = np.array([1.2, 6.0, 4.3, 2.1])

a

array([1.2, 6. , 4.3, 2.1])

In [4]:
# 指数をとる
exp_a = np.exp(a)

exp_a

array([  3.32011692, 403.42879349,  73.6997937 ,   8.16616991])

In [5]:
# 合計を計算
sum_exp_a = np.sum(exp_a)

sum_exp_a

488.61487402763504

In [6]:
# 入力を割る
y = exp_a / sum_exp_a

y

array([0.00679496, 0.82565803, 0.15083412, 0.0167129 ])

In [7]:
np.sum(y)

1.0

## 関数を作ろう

In [8]:
def softmax(a):
    # ↓ここに書いてね


    return y

In [9]:
a = np.array([1.2, 6.0, 4.3, 2.1])

softmax(a)

array([0.00679496, 0.82565803, 0.15083412, 0.0167129 ])

In [10]:
# ↓↓適当な配列を作って試してみよう↓↓
x = 

softmax(x)

SyntaxError: invalid syntax (924531583.py, line 2)

## オーバーフローに注意！！
Pythonでは小数型`float`に無限大を示す値`inf`が存在するのでエラーは起きません。
代わりにWarningが出るようになっています。

↓実行してみよう

In [ ]:
exp1000 = np.exp(1000)

exp1000

/var/folders/mk/4l2s4ftj18sgrl6l79zdx1p40000gn/T/ipykernel_97447/2020616344.py:1: RuntimeWarning: overflow encountered in exp
  exp1000 = np.exp(1000)


inf

In [ ]:
float('inf') * 0

nan

### オーバーフロー回避

先に最大値を引いておきます

In [ ]:
a = np.array([1010, 1000, 900])

# ↓inf       ↓inf
np.exp(a) / np.sum(np.exp(a))

/var/folders/mk/4l2s4ftj18sgrl6l79zdx1p40000gn/T/ipykernel_97447/621659176.py:3: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))
/var/folders/mk/4l2s4ftj18sgrl6l79zdx1p40000gn/T/ipykernel_97447/621659176.py:3: RuntimeWarning: invalid value encountered in true_divide
  np.exp(a) / np.sum(np.exp(a))


array([nan, nan, nan])

In [ ]:
a_max = np.max(a)  # 最大値

a - a_max

array([   0,  -10, -110])

In [ ]:
np.exp(a - a_max) / np.sum(np.exp(a - a_max))

array([9.99954602e-01, 4.53978687e-05, 1.68883521e-48])

### 関数にまとめよう

In [ ]:
def softmax(a):
    # ↓ここにコードを書いてね

    return y

In [ ]:
a = np.array([1000, 1001, 999])

softmax(a)